apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: entigo-demo-bucket
  labels:
    testing.upbound.io/example-name: s3
spec:
  forProvider:
    region: eu-north-1
    tags:
      Name: SampleBucket
  providerConfigRef:
    name: aws-provider-config
  writeConnectionSecretToRef:
      namespace: default
      name: entigo-demo-bucket
      